project:
  type: website
  output-dir: _site

website:
  title: "Advanced Stock Charting"
  navbar:
    background: "#141824"
    search: false
    left:
      - text: "Home"
        href: index.qmd
      - text: "Stock Indices"
        menu:
          - text: "Apple (AAPL)"
            href: aapl_index.qmd
          - text: "Microsoft (MSFT)"
            href: msft_index.qmd
          - text: "NVIDIA (NVDA)"
            href: nvda_index.qmd
          - text: "Tesla (TSLA)"
            href: tsla_index.qmd
      - text: "Roadmap"
        href: project_outline.qmd

format:
  html:
    theme: [cosmo, theme.scss]
    page-layout: full
