project:
  type: website
  output-dir: _site

website:
  title: "Advanced Stock Charting"
  navbar:
    background: "#141824"
    search: false
    left:
      - text: "Home"
        href: index.qmd
      - text: "Stock Indices"
        href: stock_indices.qmd
      - text: "Roadmap"
        href: project_outline.qmd

format:
  html:
    theme: [cosmo, theme.scss]
    page-layout: full
